---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Basic API - Lambda and Dynamodb using SAM
Parameters:
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '10'
    MinValue: '5'
    MaxValue: '10000'
Globals:
  Function:
    Runtime: python3.6
    Timeout: 5
    MemorySize: 128
    Environment:
      Variables:
        STACKNAME: !Ref "AWS::StackName"
Resources:
  ping:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/
      Handler: ping.main
      AutoPublishAlias: dev
      Role: <existing_role>   # So that deployment agent doesn't need Iam permissions
      Events:
        Endpoint:
          Type: Api
          Properties:
            Path: /bet/ping
            Method: GET
  StageData:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${AWS::StackName}-StageData"
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'
      Tags:
        StackName: !Sub "${AWS::StackName}"
Outputs:
  LEDApiURL:
    Description: API endpoint URL for LED
    Export:
      Name: !Sub "${AWS::StackName}-Endpoint"
    Value: !Join
      - '.'
      - - !Sub "https://${ServerlessRestApi}"
        - execute-api
        - !Ref AWS::Region
        - amazonaws.com/Prod
