---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cashflow Model endpoint
Globals:
  Function:
    Runtime: python3.6
    Timeout: 300
    MemorySize: 128
    Environment:
      Variables:
        STACKNAME: !Ref "AWS::StackName"
Resources:
  ModelLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: TealLambda-Python36-StatsModel
      ContentUri: pd_sm_layer
      Description: Layer for modeling function
      CompatibleRuntimes:
        - python3.6
      RetentionPolicy: Delete
  cashflowmodel:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-cashflowmodel"
      CodeUri: lambdas/
      Handler: cashflowmodel.main
      AutoPublishAlias: dev
      Layers:
        # Use AWS Numpy lambda
        - arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python36-SciPy1x:2
        - !Ref ModelLayer

Outputs:
  cashflowmodelARN:
    Description: Lambda ARN to call model via
    Export:
      Name: !Sub "${AWS::StackName}-cashflowmodelARN"
    Value: !GetAtt cashflowmodel.Arn
